.TH "KBLUEPROXIMITY" "1" "September 04, 2026" "Marco Faenzi" ""
.SH NAME
kblueproximity \- locks/unlocks your desktop tracking a bluetooth device
.SH SYNOPSIS
.B kblueproximity
.SH DESCRIPTION
.B kblueproximity
is a Qt6 / KDE desktop utility that locks and unlocks the screen based on
the Bluetooth proximity of a paired device (typically a mobile phone).
.PP
Have a look at the package documentation in your distribution's doc directory, likely /usr/share/doc/kblueproximity, or visit the project website.
.PP
.B kblueproximity
stores its configuration under
.I ~/.kblueproximity/
.SH AUTHOR
KBlueProximity is based on BlueProximity by Lars Friedrichs <larsfriedrichs@gmx.de>.
